Add query method to the Database connection class
tareq1988/wp-eloquent pull request #53
Opened 2019-05-09 12:59 UTC by polevaultweb

To return \Illuminate\Database\Query\Builder object. 

Resolves https://github.com/tareq1988/wp-eloquent/issues/52

2019-05-09 14:22 UTC, roskno requested changes
Hi @polevaultweb .

I think you should also change the **table** function to something like that to keep it as close as possible to the original class.

` public function table($table)
    {
	    $table = $this->db->prefix . $table;
        return $this->query()->from($table);
    }`

What do you think?

Cheers!!

2019-05-10 07:34 UTC, roskno commented
Hi,

Models aren't working either. These changes also fix this:

`PHP Fatal error:  Uncaught Error: Call to undefined method WeDevs\ORM\Eloquent\Database::query() in /Applications/MAMP/htdocs/woosync/wp-content/plugins/atum-export-pro/vendor/illuminate/database/Eloquent/Model.php:1047`

2019-05-21 10:35 UTC, polevaultweb commented
@roskno i think the table method changes are outside of the scope of this fix

2019-06-07 17:08 UTC, rahilwazir commented
@tareq1988 Please merge this.

2019-07-24 11:27 UTC, calogeroguagenti commented
@tareq1988 Any luck to have this PR merged, please? Thanks for your fantastic work!

2019-07-25 06:13 UTC, merged

2019-07-25 06:59 UTC, calogeroguagenti commented
@tareq1988  You are a HERO! Thank you 👐